name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - brotlipy=0.7.0=py39h27cfd23_1003
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py39h06a4308_0
  - cffi=1.14.6=py39h400218f_0
  - chardet=4.0.0=py39h06a4308_1003
  - conda=4.10.3=py39h06a4308_0
  - conda-package-handling=1.7.3=py39h27cfd23_1
  - cryptography=3.4.7=py39hd23ed53_0
  - idna=2.10=pyhd3eb1b0_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.1.3=py39h06a4308_0
  - pycosat=0.6.3=py39h27cfd23_0
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.5=h12debd9_4
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py39h27cfd23_0
  - setuptools=52.0.0=py39h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - tqdm=4.61.2=pyhd3eb1b0_1
  - tzdata=2021a=h52ac0ba_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
prefix: /opt/conda
